### PR TITLE
Add support for hstore type in PostgreSQL

### PR DESCRIPTION
**Pull request by arustleund**
Added support for the hstore type from PostgreSQL, including most binary operations. See https://www.postgresql.org/docs/current/hstore.html

### CODE REVIEW

**Comment by vincentlauvlwj** [comment]
1. Please make sure that the build success and all checks pass (detekt, unit tests, etc.). 
2. Update the `build.gradle` file, add your GitHub ID to the developers info (line 85).

**Comment by vincentlauvlwj** [comment]
For example, implement the delete operator like this: 

```kotlin
operator fun ColumnDeclaring<Hstore>.minus(key: String): HstoreBinaryExpression<String, Hstore> {
    return HstoreBinaryExpression(DeleteKey, asExpression(), ArgumentExpression(key, VarcharSqlType))
}
```

Then the usage will be: 

```kotlin
database.update(Metadatas) {
    it.attributes to (it.attributes - "key")
    where { it.id eq 1 }
}
```

**Comment by arustleund** [comment]
> Would it be better to implement these hstore operators by overloading some Kotlin builtin operators?
Yes, I really wanted to do this, unfortunately, when I tried it out, there was method signature clash between, for example, the deleteKey and deleteKeys functions. When they're both named "minus" the compiler doesn't see any different between the version that takes `ColumnDeclaring` as an argument. I could only do this for one of the functions per operator, and I thought it was weird to have an operator for "delete key", but not for "delete keys". I suppose we could overload + for concat, but I thought for consistency's sake to use normal names for all of them.

**Comment by vincentlauvlwj** [comment]
We can use the `@JvmName` annotation to avoid signature clashes, see https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html#handling-signature-clashes-with-jvmname

**Comment by arustleund** [comment]
I forgot about that feature! Good idea. I've made those changes but now Codacy is unhappy I think because I have 6 minus methods.

**Comment by vincentlauvlwj** [comment]
Merged, will release in next version.

**Pull request merged**
